spring:
  data:
    redis:
      password: ${REDIS_PASSWORD:your-redis-password}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/your_database}
    username: ${POSTGRES_USER:your-db-username}
    password: ${POSTGRES_PASSWORD:your-db-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 6MB

redis:
  host: ${REDIS_HOST:localhost}

minio:
  user: ${MINIO_USERNAME:your-minio-username}
  password: ${MINIO_PASSWORD:your-minio-password}
  endpoint: ${MINIO_ENDPOINT:your-minio-endpoint}
  bucketNames:
    image-bucket: images
    trash-bucket: trash
    profile-image-bucket: profile-image

server:
  port: 8082

card:
  images:
    count: 6

microservices:
  x-api-key: ${X_API_KEY:your-api-key}
  authentication:
    prefix: http://
    host: ${AUTHENTICATION_HOST:localhost}
    port: 8083
    endpoints:
      validateToken: /auth/validate
      addProfileImage: /user/addProfileImage
      user: /user/get

