spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:LOCAL_POSTGRES_PORT/DATABASE_NAME}
    username: ${SPRING_DATASOURCE_USERNAME:LOCAL_POSTGRES_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD:LOCAL_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 6MB

minio:
  user: ${MINIO_USERNAME:LOCAL_MINIO_USERNAME}
  password: ${MINIO_PASSWORD:LOCAL_MINIO_PASSWORD}
  endpoint: ${MINIO_ENDPOINT:localhost}
  bucketNames:
    image-bucket: images
    trash-bucket: trash
    profile-image-bucket: profile-image

server:
  port: 8082

card:
  images:
    count: 6

microservices:
  x-api-key: ${X_API_KEY:local-api-key}
  authentication:
    prefix: http://
    host: ${AUTHENTICATION_HOST:localhost}
    port: 8083
    endpoints:
      validateToken: /auth/validate
      addProfileImage: /user/addProfileImage
