rabbitmq:
  queue:
    recovery:
      name: recovery-queue
    email:
      name: email-queue
  exchange: finder-exchange
  routing-key:
    email:
      name: email-routing-key
    recovery:
      name: recovery-routing-key

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:your-rabbitmq-username}
    password: ${RABBITMQ_DEFAULT_PASS:your-rabbitmq-password}
  mail:
    host: ${SMTP_HOST:smtp.your-mail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_MAIL:your-email@example.com}
    password: ${SMTP_PASSWORD:your-smtp-password}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085
