spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:LOCAL_POSTGRES_PORT/DATABASE_NAME}
    username: ${SPRING_DATASOURCE_USERNAME:LOCAL_POSTGRES_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD:LOCAL_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

redis:
  host: ${REDIS_HOST:localhost}

microservices:
  x-api-key: ${X_API_KEY:local-api-key}
  authentication:
    prefix: http://
    host: ${AUTHENTICATION_HOST:localhost}
    port: 8083
    endpoints:
      validateToken: /auth/validate
      getUserByToken: /auth/get-user
      linkCommentAndUser: /auth/user/addComment
      unlinkCommentAndUser: /auth/user/comment/del