spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:LOCAL_POSTGRES_PORT/DATABASE_NAME}
    username: ${POSTGRES_USER:LOCAL_POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD:LOCAL_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      password: ${REDIS_PASSWORD:REDIS_LOCAL_PASSWORD}

server:
  port: 8081

redis:
  host: ${REDIS_HOST:localhost}

microservices:
  x-api-key: ${X_API_KEY:local-api-key}
  authentication:
    prefix: http://
    host: ${AUTHENTICATION_HOST:localhost}
    port: 8083
    endpoints:
      validateToken: /auth/validate
      user: /user/get
      linkCommentAndUser: /user/addComment
      unlinkCommentAndUser: /user/comment/del