rabbitmq:
  queue:
    recovery:
      name: recovery-queue
  exchange: finder-exchange
  routing-key:
    recovery:
      name: recovery-routing-key

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:LOCAL_RABBITMQ_LOGIN}
    password: ${RABBITMQ_DEFAULT_PASS:LOCAL_RABBITMQ_PASSWORD}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:LOCAL_POSTGRES_PORT/DATABASE_NAME}
    username: ${POSTGRES_USER:LOCAL_POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD:LOCAL_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      password: ${REDIS_PASSWORD:REDIS_LOCAL_PASSWORD}

redis:
  host: ${REDIS_HOST:localhost}

server:
  port: 8083

jwt:
  secret-key: your-secret-key

microservices:
  x-api-key: ${X_API_KEY:local-api-key}
  auth:
    prefix: http://
    host: localhost
    endpoints:
      recovery-password: /user/recovery/password
  ads:
    prefix: http://
    host: ${ADS_HOST:localhost}
    port: 8080
    endpoints:
      delCard: /card/del
      getUserCards: /card/getUserCards
      delAllComplaintByUserId: /complaint/dellAllByUser
  image:
    prefix: http://
    host: ${IMAGE_HOST:localhost}
    port: 8082
    endpoints:
      moveImage: /image/move
      moveProfileImage: /image/profile/move
      delImageFromMinio: /image/del
      profileImage: /image/get-one